runtime: python312
# Limit the number of instances to limit costs to keep it under the free quota.
# More details available at: https://cloud.google.com/appengine/docs/managing-costs
automatic_scaling:
  max_instances: 1

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
